# Generated by Django 2.2.6 on 2019-10-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='is_activated',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='advuser',
            name='default_image',
            field=models.ImageField(default='main.png', upload_to='', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Почтовый ящик'),
        ),
    ]
