# Generated by Django 2.2.6 on 2019-10-23 14:54

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191022_2158'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='advuser',
            managers=[
                ('objects', shop.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='advuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email'),
        ),
    ]
