# Generated by Django 2.2.6 on 2019-10-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_advuser_photo_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='photo_max',
            field=models.URLField(default='2', verbose_name='вк'),
        ),
    ]
