# Generated by Django 2.2.6 on 2019-10-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_advuser_photo_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='suka',
            field=models.CharField(default=2, max_length=1),
        ),
    ]
