# Generated by Django 2.2.6 on 2019-10-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_advuser_suka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='photo_max',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='suka',
        ),
    ]
